[package]
name = "blitz-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Wire protocol for BlitzDB"

[dependencies]
blitz-types = { path = "../blitz-types" }
thiserror = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
