[package]
name = "blitz-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI tool for BlitzDB"

[[bin]]
name = "Blitz"
path = "src/main.rs"

[dependencies]
blitz-types = { path = "../blitz-types" }
blitz-core = { path = "../blitz-core" }
blitz-server = { path = "../blitz-server" }
blitz-runtime = { path = "../blitz-runtime" }
blitz-protocol = { path = "../blitz-protocol" }
bytes = { workspace = true }
semver = "1"
thiserror = { workspace = true }
clap = { version = "4", features = ["derive"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
